<?php
/**
 * @var Hello $block
 */

use SimpleField\HelloModule\Block\Html\Hello;

$productCollection = $block->getProductCollection();
?>
<table style="border:2px solid black;">
    <tr>
        <th>Nazwa</th><th>Cena</th>
    </tr>
    <?php foreach ($productCollection as $product) { ?>
        <tr>
            <td><?php echo $product->getName()?></td>
            <td><?php echo $product->getPrice()?></td>
        </tr>
    <?php } ?>
</table>
