<?php
/**
 * @var Hello $block
 */

use SimpleField\HelloModule\Block\Html\Hello;

$config = $block->getDataSet();
$test = $block->getAllProducts();
?>


<?php if ($config == 1) : ?>

<table style="border:2px solid black;">
    <tr>
        <th>Nazwa</th>
        <th>Cena</th>
    </tr>
    <?php foreach ($test as $product) : ?>
        <tr>
            <td><?php echo $product->getName() ?></td>
            <td><?php echo $product->getPrice() ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<?php else: echo "Zaznacz YES w konfiguracji, aby zobaczyc liste produktów"; endif;?>
